### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by fedorova** [1a1a11a/libCacheSim#36]
The documentation in [develop/doc/advanced_lib_extend.md](https://github.com/1a1a11a/libCacheSim/blob/develop/doc/advanced_lib_extend.md) says:

> Add command line option in [bin/cachesim/cli.c](https://github.com/1a1a11a/libCacheSim/blob/develop/libCacheSim/bin/cachesim/cli.c) so that you can use cachesim binary.

There isn't such a file. I think one needs to add the new algorithm to the doc array in cli_parser.c and the string comparison clause with the new initialization function in cache_init.h.

**Comment by 1a1a11a** [comment]
Good catch! I have updated the doc! Thank you!
