### ISSUE TITLE
Error when running the cacheCluster example

### ISSUE THREAD

**Issue by LydiaNosali** [1a1a11a/libCacheSim#37]
There's an error (see picture) I am getting when I try to run the cacheCluster example.
![error](https://github.com/1a1a11a/libCacheSim/assets/49485668/229147c1-2318-4dbe-b731-353ebbf78637)

**Comment by 1a1a11a** [comment]
Is this still an issue?

**Comment by LydiaNosali** [comment]
Yes

**Comment by LydiaNosali** [comment]
> Is this issue fixed?

No, I couldn't fix this issue. I think it has something to do with the libraries installed that are not up-to-date with the code.

**Comment by 1a1a11a** [comment]
I will take a look. :)

**Comment by LydiaNosali** [comment]
> I will take a look. :)

Hi, did you figure out the solution to the problem?

**Comment by 1a1a11a** [comment]
Thank you! This is fixed now.
