### ISSUE TITLE
Question: Understanding Units in Trace Data

### ISSUE THREAD

**Issue by haomactracy** [1a1a11a/libCacheSim#38]
Hi，
i want to ask 2 question，
1.
in trace.csv, the unit of every cols is
version, time(ms or s ?), op, size(byte), lbn(512B,sector)?
2.
struct {
    uint32_t timestamp;
    uint64_t obj_id;
    uint32_t obj_size;
    int64_t next_access_vtime;  // -1 if no next access
}
what are the units of timestamp and next_access_vtime, if we have timestamp, why we need next_acess_vtime

thanks

**Comment by haomactracy** [comment]
here are strips in trace.csv
1,5633898,2a,512,42932745
1,5633898,2a,512,42932746
1,5633898,2a,512,42932747

**Comment by haomactracy** [comment]
the second question is for twitter_cluster52.csv

what are their units
time, object(?), size(byte), next_access_vtime(ms)
0, 13053225291711363978, 737, 13
0, 61177148907475485, 248, 6570713
0, 286355432205858634, 567, 7
0, 15247269157424090910, 54, 1244
0, 4675217417842824703, 54, 1650187
0, 6006438795856014400, 253, 7142982

**Comment by 1a1a11a** [comment]
1. the trace.csv time is in sec, the next_access_time is the logical time (# requests) between current and the next request. It is used for some algorithms that require future information, e.g., Belady 
2. object id is a hash of object id (string)
