### ISSUE TITLE
how to read OracleGeneral trace，how to transfrom from csv to it

### ISSUE THREAD

**Issue by haomactracy** [1a1a11a/libCacheSim#39]
i use ztsd to decompress msr_hm_0.oracleGeneral.zst to msr_hm_0.oracleGeneral，i cannot see the exact trace，i use vim，and found full of Garbled characters，can you tell me how to read OracleGeneral trace，how to transfrom from csv to it.
thanks

**Comment by 1a1a11a** [comment]
the oracleGeneral trace is a binary trace, so you cannot direct read as txt file
we have provided a tool `tracePrint` that you can use to print the trace in plain text

to transform csv traces to oracleGeneral, we have provided `traceConv` (both are compiled by default)
take a look at the help menu and let me know if you have more questions 

BTW, if you are interested in contributing a doc on reading and converting oracleGeneral trace, it would be appreciated. :)
