### ISSUE TITLE
[ERROR] 11-26-2023 21:28:11 cache_init.h:160  (tid=140522033927552): do not support algorithm glcache

### ISSUE THREAD

**Issue by szisbest** [1a1a11a/libCacheSim#41]
hi~当我运行以下命令行
root@Samuel:/home/sz/libCacheSim/_build# ./bin/cachesim ../data/trace.vscsi vscsi glcache auto
我会显示报错：
[ERROR] 11-26-2023 21:28:11 cache_init.h:160  (tid=140522033927552): do not support algorithm glcache
请问应该如何解决？

**Comment by 1a1a11a** [comment]
To use GL-Cacche, you need to enable during compilation https://github.com/1a1a11a/libCacheSim/blob/892ff04c1a1d9dbaea868e069e2d53d3fa2a8536/CMakeLists.txt#L20 

`cmake -DENABLE_GL-CACHE=1 ..`
