### ISSUE TITLE
GLCache bug

### ISSUE THREAD

**Issue by haomactracy** [1a1a11a/libCacheSim#42]

**Comment by haomactracy** [comment]
However，when i run glcache, it do not lead to any bug, why?

**Comment by 1a1a11a** [comment]
Hi @haomactracy good catch, I believe it is a bug, but seg_feature is not used anymore, so it does not affect. If you want to send a PR, I am happy to merge it.

**Comment by haomactracy** [comment]
Why you do not use seg feature any more，does it mean glcache does not fit?
