### ISSUE TITLE
Questions about running test.c

### ISSUE THREAD

**Issue by gwanil** [1a1a11a/libCacheSim#5]
Hello

After installing it along with README.md, it runs as a test.out file
cache_t *cache = create_cache(name, common_cache_params, cache_specific_params); 
LRU, FIFO, and LFU work well here, but if you insert Random and LHD, you will get the error "cannot load internal cache" How can I write down the name to use Random and LHD?

**Comment by 1a1a11a** [comment]
Hi @gwanil, the plugin system fails sometimes, we have a new version which does not use plugin to implement cache. I will update this today. Thank you for bringing this to my attention. :)

**Comment by gwanil** [comment]
Thank you. @1a1a11a 

I am studying after reading the A Large Scale Analysis of Hundreds of In-memory Key-value Cache Clusters at Twitter paper.
It's been very helpful. 
I want to experiment with a new version as soon as possible.
Can I ask you a question if something you don't know happens during the experiment?
