### ISSUE TITLE
Set but unused variable

### ISSUE THREAD

**Issue by nwf-msr** [1a1a11a/libCacheSim#51]
`ccache_params_copy` in `Random.c` is set but not used thereafter:
https://github.com/1a1a11a/libCacheSim/blob/eeae9891003dee054ea6df2b32e3a6dff7107663/libCacheSim/cache/eviction/Random.c#L48-L51
I suspect the `ccache_params` on line 51 wants to be `ccache_params_copy` instead?

ETA: Also https://github.com/1a1a11a/libCacheSim/blob/eeae9891003dee054ea6df2b32e3a6dff7107663/libCacheSim/cache/eviction/RandomTwo.c#L49-L53

**Comment by 1a1a11a** [comment]
Good catch! Can you send PR?
