### ISSUE TITLE
Cloudphysic block trace origin format

### ISSUE THREAD

**Issue by haomactracy** [1a1a11a/libCacheSim#54]
Hi，can you provide Cloudphysic block trace origin format, i want to analyze it, but i cannot find the way to download a Cloudphsic block trace with offset and length.
Thank you so much!

**Comment by 1a1a11a** [comment]
Hi @haomactracy, you can download them here https://ftp.pdl.cmu.edu/pub/datasets/twemcacheWorkload/.cphy/

**Comment by 1a1a11a** [comment]
Hi @haomactracy , since you study the offset and length, there is another dataset from Meta that you might be interested 
https://cachelib.org/docs/Cache_Library_User_Guides/Cachebench_FB_HW_eval/#list-of-traces

**Comment by haomactracy** [comment]
> Hi @haomactracy, you can download them here https://ftp.pdl.cmu.edu/pub/datasets/twemcacheWorkload/.cphy/

**Comment by haomactracy** [comment]
Thank you so much，i download the trace with vscsitrace Binary file，can you give me some information about how to get the offset and length from the trace？Thanks

**Comment by 1a1a11a** [comment]
libCacheSim does not have the tool to print it, but take a look at `vscsi.c` and https://man.openbsd.org/vscsi.4

**Comment by haomactracy** [comment]
Thanks，but i have one question，that is，when i find the data structure of vscsi and print the trace(length and offset), 
typedef struct {
  uint32_t sn;
  uint32_t len;
  uint32_t nSG;
  uint16_t cmd;
  uint16_t ver;
  uint64_t lbn;
  uint64_t ts;
} trace_v1_record_t;
which element represents read or write
i found that the simulator do not use the op(w or r), thanks for explaination!
