### ISSUE TITLE
New version which does not use plugin to implement cache

### ISSUE THREAD

**Issue by gwanil** [1a1a11a/libCacheSim#6]
Hi.

As I said before, you said you would update the new version that does not implement the cache using the plug-in, but where did the update come from? I don't think I can find it.

**Comment by 1a1a11a** [comment]
Sorry for the delay, I am still fixing linking issue, I will push to the develop branch ASAP. I expect to finish tomorrow, but will keep you updated.

**Comment by gwanil** [comment]
Thank you for your prompt reply. I'm looking forward to the new version. :)

**Comment by 1a1a11a** [comment]
If you need this in a hurry, I can help with you using a different approach, I would expect the public version to delay further. Sorry.

**Comment by gwanil** [comment]
It's such a shame. 
What kind of approach is it possible? I'd appreciate it if you could help me.

**Comment by 1a1a11a** [comment]
If you build your binary with the library, it can compile, but if you compile and install the library, and linking your binary with the library, somehow the linking does not work. I need more time to find out why. If your case, take a look at https://github.com/1a1a11a/libCacheSim/blob/c5094fbac3862320688f4f12e588d0e0e2ff50ac/test/common.h#L124 to see other ways to create cache.

**Comment by gwanil** [comment]
Thank you. I tried the method you told me and it worked well. But I want to use the optimal, so should I remove the annotation and modify the code?

**Comment by 1a1a11a** [comment]
What do you mean by annotation? If you mean comment, yeah, give it a try.
