### ISSUE TITLE
How do you warm up?

### ISSUE THREAD

**Issue by gwanil** [1a1a11a/libCacheSim#7]
[Juncheng Yang, Yao Yue, Rashmi Vinayak, A large scale analysis of hundreds of in-memory cache clusters at Twitter. 14th USENIX Symposium on Operating Systems Design and Implementation (OSDI 20), 2020]

In this paper, it says that I warmed up 5 days in Sector 6.2  Simulation Setup, but I don't know how to warm up traces except for open_trace when I used a simulator. How can I warm up while using Quickstart? I downloaded the trace used in the current experiment.

**Comment by 1a1a11a** [comment]
you can read requests from the trace, send to cache, continue until the a certain criteria (e.g. 5 days of requests) 
The flow is 1. create a reader, 2. create a cache, 3. read the first request, send to cache, 4. loop step 3 till the the request is 5 days after the first request

**Comment by gwanil** [comment]
Currently, I want to download trace from Snia and do an experiment through test.c. To do that, I want to warm up the data for 5 days and measure the miss ratio through the trace for 1 day, should I read the trace format as txt or binary?

**Comment by 1a1a11a** [comment]
Yes. You can try both, we have been using binary trace, but it also supports plain text as well.
