### ISSUE TITLE
"obj-id-is-num" parameter doesn't support hex values

### ISSUE THREAD

**Issue by Helen0721** [1a1a11a/libCacheSim#70]
Inside tracePrint and traceConv.

Example input: 
time,object,size,next_access_vtime
604038471,82131353f9ddc8c6,87,-1
604038471,a54f88ab02ece24d,0,-1
604038471,a54f88ab02ece24d,0,-1
604038471,a54f88ab02ece24d,0,-1
604038471,a54f88ab02ece24d,0,-1

tracePrint says "object id is not numeric a54f88ab02ece24d"

**Comment by 1a1a11a** [comment]
`obj-id-is-num` supports hex value, however, it recognizes the value if it starts with 0x. It is non-trivial to support hex value if it does not start with 0x. Will not support this.
