### ISSUE TITLE
Using the Setup a binary reader in the libCache SimQuickstart document

### ISSUE THREAD

**Issue by gwanil** [1a1a11a/libCacheSim#8]
Thank you for your answer to the last issue. I want to use the same way as binary trace, but there is a problem. 

reader_init_param_t init_params_bin = {};
reader = setup_reader(filename, BIN_TRACE, OBJ_ID_NUM, &init_params_bin);

If you look at quickstart.md,
reader_init_param_t init_params_bin = {.binary_fmt="<3I2H2Q", .obj_size_field=2, .obj_id_field=6, };

You gave me an example like this, but I don't understand exactly what to write on binary_fmt and field. Can you help me?

**Comment by gwanil** [comment]
Thank you. As you told me, I opened the trace after looking at the twrBin.h file.
reader_t* reader = open_trace("/hdd/cluster18.000", TWR_TRACE, OBJ_ID_STR, NULL);

When I do this, I give the variable "i"

 35   while (read_one_req(reader, req) == 0) {
 36   if (cache->get(cache, req) == cache_ck_miss) {
 37   miss_byte += req->obj_size;
 38   miss_cnt++;
 39   }
 40   i++;
 41   req_byte += req->obj_size;
 42   }
I checked "i" By the way, the number of lines in the trace file and the number of total come out differently, is this correct?

**Comment by 1a1a11a** [comment]
sorry, has the problem been solved?

**Comment by gwanil** [comment]
Yes, it's solved. It was my fault.
