### ISSUE TITLE
Glib-ERROR

### ISSUE THREAD

**Issue by gwanil** [1a1a11a/libCacheSim#9]
The following error occurred when I opened trace while running the program.

What kind of problem?

(process:8155): GLib-ERROR **: 10:10:40.250: ../../../../glib/gmem.c:105: failed to allocate 49463296 bytes
Trace/breakpoint trap (core dumped)

**Comment by 1a1a11a** [comment]
It looks like you ran out of memory, how much DRAM do you have?

**Comment by gwanil** [comment]
Memory on the server.

root@dbms:~# free -h
              total        used        free      shared  buff/cache   available
Mem:            62G        475M         62G         16K        148M         61G
Swap:          9.0G        102M        8.9G

**Comment by 1a1a11a** [comment]
hmm, it would be good if you have stack trace.

**Comment by gwanil** [comment]
I tried to figure out the stack with gdb, but it says I can't.

So I looked at the problem with dmeseg.

=================================
(gdb) p main
$1 = {int (int, char **)} 0x555555554c90 <main>
(gdb) r
Starting program: /root/libCacheSim/_build/c18.back.out 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
filename = /hdd/cluster22.000

Program terminated with signal SIGKILL, Killed.
The program no longer exists.
(gdb) bt
No stack.
(gdb) 
======================================

[188077.776581] [14560]     0 14560 20101354 16210629 150704128  2311952             0 c18.back.out
[188077.776582] [14597]     0 14597     1546       16    53248        0             0 sleep
[188077.776584] Out of memory: Kill process 14560 (c18.back.out) score 956 or sacrifice child
[188077.777441] Killed process 14560 (c18.back.out) total-vm:80405416kB, anon-rss:64842516kB, file-rss:0kB, shmem-rss:0kB

I don't know why it holds 80gb... 
If you need, I will show you the test.c file that I wrote

**Comment by gwanil** [comment]
`#include <libCacheSim.h>
#define W 20	// total trace read
#define F 72	// use one-day trace
int main(int argc, char *argv[])
{
        unsigned long i = 0;	// total check
	long miss_cnt = 0;	
	long miss_cnt2 = 0;
	int a;
	reader_t* reader;
	request_t* req =  new_request();
	char filename[50];

	common_cache_params_t cc_params = {.cache_size=1024*1024*1024};	// cache_size check
	cache_t *cache = create_cache("LRU", cc_params, NULL);		// alg 
	cache_t *cache2 = create_cache("FIFO", cc_params, NULL);
	
	int64_t req_byte = 0, miss_byte = 0;

	for (a = 0; a <= W; a++) {
		
			sprintf(filename, "/hdd/cluster22.%03d", a);
			printf("filename = %s\n ", filename);

		
		reader_init_param_t init_params_csv = {.delimiter=',', .real_time_field=1, .obj_id_field=2, .ttl_field=7, .has_header=FALSE};
        reader = open_trace(filename, CSV_TRACE, OBJ_ID_STR, &init_params_csv);


	if (a == W) {
		while (read_one_req(reader, req) == 0) {
			i++;
			if (cache->get(cache, req) == cache_ck_miss) {
				miss_cnt++;
			}
			if (cache2->get(cache2, req) == cache_ck_miss) {
				miss_cnt2++;
			}
		}

		printf("========LRU=======\n");
		printf("total:%lu\n", i);
  		printf("hit_rate:%f\n", ((float)i-(float)miss_cnt)/(float)i*100);
 		printf("miss_rate:%f\n",(float)miss_cnt/(float)i*100);
 		printf("======================\n");
 		printf("========FIFO=======\n");
  		printf("total:%lu\n", i);
  		printf("hit_rate:%f\n", ((float)i-(float)miss_cnt2)/(float)i*100);
  		printf("miss_rate:%f\n",(float)miss_cnt2/(float)i*100);
  		printf("======================\n");
	}else if(a >= F){

		while (read_one_req(reader, req) == 0) {
			i++;
			if (cache->get(cache, req) == cache_ck_miss) {
				miss_cnt++;
			}
			if (cache2->get(cache2, req) == cache_ck_miss) {
				miss_cnt2++;
			}
		}
	}else{
		while (read_one_req(reader, req) == 0) {
			if (cache->get(cache, req) == cache_ck_miss) {
			}
			if (cache2->get(cache2, req) == cache_ck_miss) {
			}
		}
	}
	close_trace(reader);
	}
	free_request(req);
	cache->cache_free(cache);
	cache2->cache_free(cache2);
	return 0;
}
`

**Comment by 1a1a11a** [comment]
is the problem solved?

**Comment by gwanil** [comment]
No, some run for each trace and others don't. I haven't solved it yet.

**Comment by 1a1a11a** [comment]
How do you setup the reader?

**Comment by 1a1a11a** [comment]
you did not specify obj_size_col, then each object will be size 1, and you give a cache size of 1024*1024*1024, which means the cache will have 1024*1024*1024 objects, each object will use 10s bytes, so it may use more than 64 GB DRAM. 
You can try to 1. specify the obj_size_col 2. reduce the cache size

**Comment by gwanil** [comment]
Thank you. I'll try again in the way you told me.

**Comment by gwanil** [comment]
Can I know the location of obj_size_col? I can't find it.

**Comment by gwanil** [comment]
Oh!
I was originally going to add this, but I couldn't because I didn't know how to specify it because the trace has cache_size_field with key and value.

![image](https://user-images.githubusercontent.com/55725509/193979334-75a5ee51-f5cd-40a9-bae0-7dbe1d75ae46.png)


How should I write the field when the trace is like this?

**Comment by 1a1a11a** [comment]
1. you can write a new trace reader
2. you can preprocess the trace and add a new column 
3. you can use the value size to approximate object size (not recommend)

**Comment by gwanil** [comment]
Which reader format should I use to use Method 1? Originally, I tried to use txt, but it was not available due to a similar error, and there was an error in other formats.

**Comment by 1a1a11a** [comment]
you need to create a trace reader under `libCacheSim/traceReader/` that can parse the data set you use

**Comment by gwanil** [comment]
I'll give it a try.

**Comment by 1a1a11a** [comment]
It looks like you do not specify object size field? In this case, each object is 1 byte, 1GB cache can store 1e9 objects. Is this what you want?

**Comment by gwanil** [comment]
At first, I tried to specify an object size field, but I didn't write it because I didn't know how to assign both sizes because the object size is key and value, as shown in the image above.

**Comment by 1a1a11a** [comment]
what image?

**Comment by 1a1a11a** [comment]
somehow the previous message was delayed
let me know if you have any question, if not I will close this.
