### ISSUE TITLE
Question about handling block traces

### ISSUE THREAD

**Issue by yanniszark** [1a1a11a/libCacheSim#99]
Hi!

First of all thanks a lot for releasing libcachesim in the open!
My use-case is mainly block traces, which represent requests to disks.
Since disks are split into 4k blocks (pages) and that's what the OS is caching, I was wondering how libcachesim is handling this.
Does it split big requests or maybe expect the trace to be pre-split?

**Comment by 1a1a11a** [comment]
Hi @yanniszark 
Thank you for your interest! libCacheSim does not assume any use case, so you will need to preprocess the traces into 4K blocks, or you can write your own traceReader to split the trace on the fly, see [here](https://github.com/1a1a11a/libCacheSim/tree/develop/libCacheSim/traceReader).
